[build]
  command = "npm run build:netlify"
  publish = "public"

[build.environment]
  NODE_VERSION = "20"
  GATSBY_SKIP_VALIDATE_ENGINES = "1"
  # Force skip Rendering Engines validation on Netlify by making
  # functions target differ from the build machine platform/arch.
  GATSBY_FUNCTIONS_PLATFORM = "darwin"
  GATSBY_FUNCTIONS_ARCH = "arm64"
  # Set in Netlify UI for production GA4 tracking
  # GATSBY_GA_MEASUREMENT_ID = "G-XXXXXXXXXX"


[[redirects]]
  from = "/sitemap_index.xml"
  to = "/sitemap-index.xml"
  status = 200
  force = true

